spring:
  application:
    name: config-service
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/config

eureka:
  client:
    service-url:
      defaultZone: ${DISCOVERY_SERVICE_URL:http://discovery-service:8761/eureka/}
    register-with-eureka: true
    fetch-registry: false
  instance:
    prefer-ip-address: true